id: P010501
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13785
  title: དགེ་བའི་བཤེས་གཉེན་བསྟེན་ཚུལ་གྱི་རྣམ་གཞག་བླང་དོར་གསལ་བའི་མེ་ལོང་།
  author: ''
  volumes:
    57ec819e16a84beb81c03c2b7eb75a5e:
      image_group_id: I1KG15348
      title: ''
      volume_number: 1
      total_pages: 90
      base_file: v001.txt
