id: IAC4AEAAE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:40:30+00:00'
last_modified: '2022-06-08T14:03:53.381393+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13785
  title: དགེ་བའི་བཤེས་གཉེན་བསྟེན་ཚུལ་གྱི་རྣམ་གཞག་བླང་དོར་གསལ་བའི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    FF7B:
      image_group_id: I1KG15348
      title: ''
      total_pages: 90
      order: 1
      base_file: FF7B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
